Repository coollabsio/coolify-docs, pull requests merged in 2025-02, with the labels that each got.

#184 fix: correct S3 documentation link to prevent 404
  docs/databases/backups.md
Labels: 🐞 Bug

#186 Update laravel.md
  docs/applications/laravel.md
Labels: ⚖️ Medium Priority

#190 chore: update command lines to match the current container setup.
  docs/knowledge-base/commands.md
Labels: ✨ Enhancement, ⚖️ Medium Priority
