Repository coollabsio/coolify-docs, pull requests merged in 2025-03, with the labels that each got.

#215 fix: 404 in raspberry-pi-os.md
  docs/knowledge-base/how-to/raspberry-pi-os.md
Labels: ⏱️ PR - Waiting for Changes

#180 fix: trailing slashes redirecting to landing
  nginx/nginx.conf
Labels: ⚖️ Medium Priority

#174 Add Dockerfile with Nginx Unit for Laravel deployment
  .gitignore
  docs/applications/laravel.md
Labels: ✨ Enhancement, 🐢 Low Priority

#206 feature(discovery): add Trieve search and AI chat to the docs (old Mintlify functionality)
  .github/workflows/update-trieve.yml
  .gitignore
  docs/.vitepress/config.mts
  docs/.vitepress/theme/index.ts
  docs/public/trieve-user-script.js
Labels: ⚠️ High Priority

#225 2 Fixes: 1 - blank text in <code> on light mode hover and 2 - copy button on light mode
  docs/.vitepress/theme/style.css
Labels: ⚠️ High Priority
